# Configuration File
#
# rootsite is the FogBugApi url
# timezone is the icann names for the timezone and
#   all times will have this timezone applied to them
#   dates in the UI, FogBugz dates are stored in UTC
# https://github.com/go-yaml/yaml
user: cnicholson@electsolve.com
password: "Qhh$*UB!WH2tensSHofl&Hu6"
rootsite: https://electsolve.fogbugz.com/api.asp
timezone: America/Chicago
